// src/pages/TermsPage.jsx
import React from "react";
import { Link } from "react-router-dom";
import { FileText } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-bg text-text p-6 md:p-16 max-w-3xl mx-auto">
      <Link to="/" className="text-primary text-sm font-bold mb-8 inline-flex items-center gap-2 hover:underline">
        ← Back to Home
      </Link>

      <div className="flex items-center gap-3 mb-10 mt-4">
        <div className="w-12 h-12 bg-primary/10 rounded-2xl flex items-center justify-center text-primary">
          <FileText size={24} />
        </div>
        <div>
          <h1 className="text-3xl font-black text-text">Terms of Service</h1>
          <p className="text-text-muted text-sm">Last updated: May 2025</p>
        </div>
      </div>

      <div className="space-y-8 text-text-muted leading-relaxed">
        <section>
          <h2 className="text-xl font-bold text-text mb-3">1. Acceptance</h2>
          <p>By creating an account on ExamPadi AI, you agree to these Terms of Service. If you do not agree, please do not use the platform.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-text mb-3">2. Service Description</h2>
          <p>ExamPadi AI provides AI-powered past questions, study tools, and exam preparation features for Nigerian students preparing for JAMB and WAEC. The platform is operated by Jadai Studios.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-text mb-3">3. Account Responsibilities</h2>
          <ul className="list-disc list-inside space-y-2">
            <li>You are responsible for maintaining the confidentiality of your account credentials</li>
            <li>You must provide accurate information during registration</li>
            <li>One account per person — sharing accounts is prohibited</li>
            <li>You must be 13 years or older to create an account</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-text mb-3">4. Free Plan Limits</h2>
          <p>Free accounts are limited to 30 questions per day. This limit resets at midnight (WAT). Circumventing this limit by creating multiple accounts is a violation of these terms and may result in account suspension.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-text mb-3">5. Payments & Subscriptions</h2>
          <ul className="list-disc list-inside space-y-2">
            <li>Pro plans are billed in advance via Paystack</li>
            <li>All prices are in Nigerian Naira (₦)</li>
            <li>Subscriptions are non-refundable once activated, except as required by Nigerian consumer protection law</li>
            <li>Plans automatically expire — they are not auto-renewed unless you initiate a new payment</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-text mb-3">6. AI-Generated Content</h2>
          <p>Explanations are generated by Groq AI. While we strive for accuracy, AI-generated content may occasionally contain errors. Do not rely solely on ExamPadi AI — always cross-reference with official JAMB/WAEC materials and textbooks.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-text mb-3">7. Prohibited Conduct</h2>
          <ul className="list-disc list-inside space-y-2">
            <li>Reverse engineering, scraping, or cloning the platform</li>
            <li>Using automated bots to generate questions in bulk</li>
            <li>Reselling or redistributing AI-generated content without permission</li>
            <li>Any activity that disrupts the service for other users</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-text mb-3">8. Termination</h2>
          <p>We reserve the right to suspend or terminate accounts that violate these terms, without refund. You may delete your account at any time by contacting <a href="mailto:jadai7065@gmail.com" className="text-primary hover:underline">jadai7065@gmail.com</a>.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-text mb-3">9. Limitation of Liability</h2>
          <p>ExamPadi AI and Jadai Studios shall not be liable for exam results, academic outcomes, or any indirect damages arising from use of the platform. The service is provided "as is."</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-text mb-3">10. Governing Law</h2>
          <p>These terms are governed by the laws of the Federal Republic of Nigeria.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-text mb-3">11. Contact</h2>
          <p>Questions? Email us at <a href="mailto:jadai7065@gmail.com" className="text-primary hover:underline">jadai7065@gmail.com</a></p>
        </section>
      </div>

      <div className="mt-16 pt-8 border-t border-border text-center">
        <p className="text-text-muted text-sm">© 2025 ExamPadi AI by Jadai Studios · <Link to="/privacy" className="text-primary hover:underline">Privacy Policy</Link></p>
      </div>
    </div>
  );
}
